### PR TITLE
Add some Wycheproof test vectors

### PR DESCRIPTION
**Pull request by daviddrysdale**
Produced from https://github.com/google/wycheproof via the tool in https://github.com/RustCrypto/utils/pull/280

### CODE REVIEW

**Comment by tarcieri** [comment]
Awesome, thank you! Looks like they're passing so far?

**Review by newpavlov — APPROVED** [review]
Looks great! But since all tests are passing, I think we can omit the description files?

**Comment by tarcieri** [comment]
They might be nice in the event of regressions, and don't look that big (especially after compression)

**Comment by newpavlov** [comment]
I am not sure how descriptions like this:
```
AES-GCM-SIV case 75 [invalid] Flipped bit 0..127 in tag
AES-GCM-SIV case 114 [valid] 
AES-GCM-SIV case 123 [invalid] Flipped bit 1 in tag
AES-GCM case 22 [valid] special case
AES-GCM case 46 [invalid] Tag changed to all zero
CHACHA20-POLY1305 case 39 [valid] 
```
would help in the event of regressions. There are some potentially useful descriptions, but considering that we always can re-generate the description files (assuming we have recorded commit hash from which they have been generated), I think it's reasonable to omit them. Plus they are useful only for development, so probably it's not worth to keep them in published crates.

**Comment by daviddrysdale** [comment]
Updated to drop the .txt files and edit the commit descriptions to include a reference to the Wycheproof source.

**Comment by newpavlov** [comment]
I think we are good to merge, but I'll leave final decision to @tarcieri.

**Review by tarcieri — APPROVED** [review]

**Pull request merged**
