### PR TITLE
chacha20poly1305 v0.1.0

### PR DESCRIPTION
**Pull request by tarcieri**
Initial release

### CODE REVIEW

**Comment by tarcieri** [comment]
@newpavlov can you add a RustCrypto team as an owner of `chacha20poly1305` so I can publish?

**Comment by newpavlov** [comment]
@tarcieri Done!

**Comment by tarcieri** [comment]
Oops. Just need to fix this up:

```
error: api errors (status 200 OK): `documentation` is not a valid url: `chacha20poly1305`
```

**Comment by newpavlov** [comment]
BTW don't forget to add `chacha20poly1305-v0.1.0` tag after you'll publish it.

**Comment by tarcieri** [comment]
@newpavlov think you might need to add me to the AEADs team:

```
error: api errors (status 200 OK): this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
```

**Comment by tarcieri** [comment]
Err, never mind. It's out! 🎉

**Comment by newpavlov** [comment]
I think it's better to publish a crate after PR has been merged. ;)

**Comment by tarcieri** [comment]
Too late 😉

**Pull request merged**
